In [ ]:
!pip install numpy



In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
lst=[[1,2,3],[4,5,6]]

In [ ]:
type(lst)

list

In [ ]:
arr=np.array(lst)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

2

In [ ]:
arr.shape


(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
zeros =np.zeros((3,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones=np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.random.random((3,3))

array([[0.51952093, 0.26740281, 0.64512121],
       [0.3212306 , 0.62616141, 0.34200446],
       [0.50987084, 0.72839345, 0.53343584]])

In [ ]:
if np.random.random()>0.5:
  print("yes")
else:
  print("no")

yes


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr=np.random.random((4,3))

In [ ]:
arr

array([[0.98549353, 0.76008336, 0.4182926 ],
       [0.69336463, 0.09687632, 0.17234095],
       [0.57301871, 0.80470141, 0.11054613],
       [0.54683107, 0.21682308, 0.37040318]])

In [ ]:
arr=np.reshape(arr,(3,4))

In [ ]:
arr

array([[0.98549353, 0.76008336, 0.4182926 , 0.69336463],
       [0.09687632, 0.17234095, 0.57301871, 0.80470141],
       [0.11054613, 0.54683107, 0.21682308, 0.37040318]])

In [ ]:
arr.flatten()

array([0.98549353, 0.76008336, 0.4182926 , 0.69336463, 0.09687632,
       0.17234095, 0.57301871, 0.80470141, 0.11054613, 0.54683107,
       0.21682308, 0.37040318])

In [ ]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

# The same functions and operations can be used for multiple matrices
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)


[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [ ]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)


[ 3 67  3 70]
[ 3 67  3 70]


In [ ]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)


[  10  360  130 3000]
[  10  360  130 3000]


In [ ]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)


[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [ ]:
# import numpy library
import numpy

# creating a numpy array of integers
arr = numpy.array([1, 5, 4, 8, 3, 7])

# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)

# printing the result
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)


maximum element in the array is:  8
minimum element in the array is:  1


In [ ]:
# import numpy library
import numpy

# creating a two dimensional
# numpy array of integers
arr = numpy.array([[11, 2, 3],
                     [4, 5, 16],
                      [7, 81, 22]])

# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)

# printing the result
print('maximum element in the array is:',
      max_element)
print('minimum element in the array is:',
      min_element)


maximum element in the array is: 81
minimum element in the array is: 2


In [ ]:
# import numpy library
import numpy

# creating a two dimensional
# numpy array of integers
arr = numpy.array([[11, 2, 3],
                     [4, 5, 16],
                      [7, 81, 22]])

# finding the maximum and
# minimum element in the array
max_element_column = numpy.max(arr, 0)
max_element_row = numpy.max(arr, 1)

min_element_column = numpy.amin(arr, 0)
min_element_row = numpy.amin(arr, 1)

# printing the result
print('maximum elements in the columns of the array is:',
      max_element_column)

print('maximum elements in the rows of the array is:',
      max_element_row)

print('minimum elements in the columns of the array is:',
      min_element_column)

print('minimum elements in the rows of the array is:',
      min_element_row)


maximum elements in the columns of the array is: [11 81 22]
maximum elements in the rows of the array is: [11 16 81]
minimum elements in the columns of the array is: [4 2 3]
minimum elements in the rows of the array is: [2 4 7]


In [ ]:
import numpy as np

# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)


# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong first axis : \n", arr2)


a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr1)


Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [ ]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print(np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print(np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print(np.sort(arr , kind = 'heapsort'))


[[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


In [ ]:
# Python program explaining
# vstack() function

import numpy as np

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = np.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [ ]:
# Python program explaining
# vstack() function

import numpy as np

# input array
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = np.vstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)


1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [ ]:
# Python program explaining
# hstack() function

import numpy as no

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [ ]:
# Python program explaining
# hstack() function

import numpy as np

# input array
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)


1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [ ]:
# Python program explaining
# numpy.concatenate() function

# importing numpy as geek
import numpy as np

arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

a = np.concatenate((arr1, arr2), axis = 0)

print (a)


[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [ ]:
# Python program explaining
# numpy.vsplit() function

# importing numpy as geek
import numpy as np

arr = np.arange(9.0).reshape(3, 3)

a = np.vsplit(arr, 1)

print (a)


[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


In [ ]:
# Python program explaining
# numpy.hsplit() function

# importing numpy as geek
import numpy as np

arr = np.arange(16.0).reshape(4, 4)

a= np.hsplit(arr, 2)

print (a)


[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr[3: ]


array([4, 5, 6, 7, 8])

In [2]:
print(arr[ : -3])
print(arr[3  :  -3])


[1 2 3 4 5]
[4 5]


In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [4]:
print(arr[ 3 , 1])
print()
print(arr[ 1: , 1:])


3

[[6 7 8]
 [7 6 5]
 [3 2 1]]


In [5]:
lst = [1,2,3,4,5,6,7,8,9,10]
for i in lst:
  if (i > 5):
    print(i)


6
7
8
9
10


In [6]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])
print(lst[lst>5]) #in a single line we have done the same thing which we did previously and this time without using the for loop


[ 6  7  8  9 10]
